# Generated by Django 2.2.4 on 2019-09-14 12:22

from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.TextField(max_length=256)),
                ('press', models.TextField(max_length=256)),
                ('classify', models.TextField(max_length=128)),
                ('name', models.TextField(max_length=128)),
                ('other', models.TextField(max_length=256)),
                ('authors', models.TextField(max_length=256)),
                ('price', models.IntegerField(default=8848996)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(max_length=20)),
                ('emailaddr', models.TextField(max_length=30)),
                ('passwd', models.TextField(max_length=20)),
                ('createdata', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.TextField(max_length=256)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdata', models.DateTimeField(auto_now_add=True)),
                ('word_list', models.DateTimeField(max_length=256)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdata', models.DateTimeField(auto_now_add=True)),
                ('recv_addr', models.TextField(max_length=256)),
                ('express_no', models.TextField(max_length=256)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.BookInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=120)),
                ('createdata', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='China',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('pid', models.ForeignKey(blank=True, db_column='pid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.China')),
            ],
            options={
                'db_table': 'china',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_img', models.FileField(upload_to=homepage.models.upload_to_of_detail_img)),
                ('cover_img', models.FileField(upload_to=homepage.models.upload_to_of_cover_img)),
                ('book_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.BookInfo')),
            ],
        ),
    ]
