# Generated by Django 2.2.4 on 2019-09-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book_price',
            field=models.IntegerField(default=88489),
        ),
    ]
