# Generated by Django 2.2.4 on 2019-09-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190914_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='China',
        ),
    ]
