# Generated by Django 2.2.4 on 2019-09-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_china'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='china',
            options={'managed': True},
        ),
    ]
