# Generated by Django 2.2.4 on 2019-09-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20190914_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='china',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.China'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='word_list',
            field=models.TextField(max_length=256),
        ),
    ]
